services:
  - type: web
    name: fastapi-shop
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build && cd ..
      python -m app.seed_data
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: NODE_VERSION
        value: 20.19.0
      - key: DEBUG
        value: false
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1